# Generated by Django 4.1.2 on 2022-10-11 06:12

import apps.core.project_requirements.utilities
import apps.geoposition.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='alt',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='alt',
            name='report',
            field=models.FileField(upload_to='Training Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='alt',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='alt',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='itc',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='itc',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='itc',
            name='report',
            field=models.FileField(upload_to='Training Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='itc',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='itc',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='lt',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='lt',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='lt',
            name='report',
            field=models.FileField(upload_to='Training Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='lt',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='lt',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='report',
            field=models.FileField(upload_to='Training Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='slspecialevent',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='slspecialevent',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='slspecialevent',
            name='report',
            field=models.FileField(upload_to='Training Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='slspecialevent',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='slspecialevent',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='wbi',
            name='comments',
            field=tinymce.models.HTMLField(verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='wbi',
            name='marked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='marked'),
        ),
        migrations.AlterField(
            model_name='wbi',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='wbi',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='submission date'),
        ),
        migrations.AlterField(
            model_name='wbi',
            name='theory_book',
            field=models.FileField(upload_to='Woodbadge Theory Books/%Y/%m', verbose_name='theory book'),
        ),
        migrations.AlterField(
            model_name='wbii',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='wbii',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='wbii',
            name='report',
            field=models.FileField(upload_to='Training Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='wbii',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='wbii',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='wbiii',
            name='assessed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='assessed'),
        ),
        migrations.AlterField(
            model_name='wbiii',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='wbiii',
            name='report',
            field=models.FileField(upload_to=' Woodbadge Assessment/%Y/%m', verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='wbiii',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
    ]
