# Generated by Django 4.1.2 on 2022-10-09 06:36

import apps.core.project_requirements.utilities
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALTProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(upload_to='Projects/Proposals/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='Proposal')),
                ('report1', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='1st Report')),
                ('report2', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='2nd Report')),
                ('report3', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='3rd Report')),
                ('completion_date', models.DateField(blank=True, help_text='Only feel when the project is complete', null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('project_description', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['scout_leader_name'],
            },
        ),
        migrations.CreateModel(
            name='CSAProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(upload_to='Projects/Proposals/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='Proposal')),
                ('report1', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='1st Report')),
                ('report2', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='2nd Report')),
                ('report3', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='3rd Report')),
                ('completion_date', models.DateField(blank=True, help_text='Only feel when the project is complete', null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('project_description', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LTProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(upload_to='Projects/Proposals/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='Proposal')),
                ('report1', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='1st Report')),
                ('report2', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='2nd Report')),
                ('report3', models.FileField(blank=True, null=True, upload_to='Projects/Reports/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='3rd Report')),
                ('completion_date', models.DateField(blank=True, help_text='Only feel when the project is complete', null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('project_description', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['scout_leader_name'],
            },
        ),
        migrations.CreateModel(
            name='UnitProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('project_description', tinymce.models.HTMLField()),
                ('detailed_report', models.FileField(upload_to='Unit Projects/%Y/%m')),
            ],
            options={
                'ordering': ['unit'],
            },
        ),
    ]
