# Generated by Django 4.1.2 on 2022-10-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitproject',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Only active Scout Leaders are valid options', limit_choices_to=models.Q(('active', True)), null=True, on_delete=django.db.models.deletion.PROTECT, to='registrations.scoutleader'),
        ),
        migrations.AddField(
            model_name='unitproject',
            name='unit',
            field=models.ForeignKey(help_text='Only verified Units are valid options', limit_choices_to=models.Q(('active', True)), on_delete=django.db.models.deletion.PROTECT, to='registrations.unit'),
        ),
        migrations.AddField(
            model_name='ltproject',
            name='scout_leader_name',
            field=models.OneToOneField(help_text='Only active Scout Leaders with training level of Three Beads are valid options', limit_choices_to=models.Q(('active', True), ('training', 'LT Course')), on_delete=django.db.models.deletion.PROTECT, to='registrations.scoutleader'),
        ),
        migrations.AddField(
            model_name='ltproject',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Only active Scout Leaders with training level of Four Beads are valid options', limit_choices_to=models.Q(('active', True), ('training', 'Four Beads')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lt_supervisor', to='registrations.scoutleader'),
        ),
        migrations.AddField(
            model_name='csaproject',
            name='jasiri_scouts',
            field=models.ManyToManyField(db_index=True, help_text='Only active Jasiri Scouts who are invested are valid options', limit_choices_to=models.Q(('section', 'Jasiri'), ('active', True), ('jasiri_investiture', True)), to='registrations.scout'),
        ),
        migrations.AddField(
            model_name='csaproject',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Only active Scout Leaders with training level of Two Beads and above are valid options', limit_choices_to=models.Q(('active', True), models.Q(('training', 'Two Beads'), ('training', 'ALT Practical'), ('training', 'ALT Project'), ('training', 'Three Beads'), ('training', 'LT Practical'), ('training', 'LT Project'), ('training', 'Four Beads'), _connector='OR')), null=True, on_delete=django.db.models.deletion.PROTECT, to='registrations.scoutleader'),
        ),
        migrations.AddField(
            model_name='altproject',
            name='scout_leader_name',
            field=models.OneToOneField(help_text='Only active Scout Leaders with training level of ALT Course are valid options', limit_choices_to=models.Q(('active', True), ('training', 'ALT Course')), on_delete=django.db.models.deletion.PROTECT, to='registrations.scoutleader'),
        ),
        migrations.AddField(
            model_name='altproject',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Only active Scout Leaders with training level of Four Beads are valid options', limit_choices_to=models.Q(('active', True), ('training', 'Four Beads')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alt_supervisor', to='registrations.scoutleader'),
        ),
        migrations.AddConstraint(
            model_name='ltproject',
            constraint=models.UniqueConstraint(fields=('scout_leader_name', 'title'), name='unique_lt_project'),
        ),
        migrations.AddConstraint(
            model_name='altproject',
            constraint=models.UniqueConstraint(fields=('scout_leader_name', 'title'), name='unique_alt_project'),
        ),
    ]
