# Generated by Django 4.1.2 on 2022-10-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altproject',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Only feel when the project is complete', null=True, verbose_name='completion date'),
        ),
        migrations.AlterField(
            model_name='csaproject',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Only feel when the project is complete', null=True, verbose_name='completion date'),
        ),
        migrations.AlterField(
            model_name='ltproject',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Only feel when the project is complete', null=True, verbose_name='completion date'),
        ),
        migrations.AlterField(
            model_name='unitproject',
            name='detailed_report',
            field=models.FileField(upload_to='Unit Projects/%Y/%m', verbose_name='detailed report'),
        ),
    ]
