# Generated by Django 4.1.2 on 2022-10-09 06:36

import apps.core.project_requirements.utilities
import apps.geoposition.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Competition Year')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('report', models.FileField(upload_to='Competition Report/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension])),
                ('level', models.CharField(choices=[('SubCounty', 'SubCounty'), ('County', 'County'), ('Regional', 'Regional'), ('National', 'National'), ('Zonal', 'Zonal')], db_index=True, max_length=15, verbose_name='Level of Competition')),
                ('venue_name', models.CharField(max_length=50)),
                ('venue', apps.geoposition.fields.GeopositionField(max_length=42)),
                ('payments', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_date'],
                'permissions': [('can_verify_Competition_payments', 'Can verify Competition payments'), ('can_edit_Competition_teams', 'Can edit Competition teams')],
            },
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Competition Year')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('level_of_competition', models.CharField(choices=[('SubCounty', 'SubCounty'), ('County', 'County'), ('Region', 'Region'), ('National', 'National'), ('Zonal', 'Zonal')], db_index=True, default='SubCounty', max_length=15, verbose_name='Level of Competition')),
                ('section', models.CharField(choices=[('Chipukizi', 'Chipukizi'), ('Mwamba', 'Mwamba'), ('Jasiri', 'Jasiri')], db_index=True, max_length=15, verbose_name='Team Section')),
                ('special', models.BooleanField(db_index=True, default=False, verbose_name='If the Team is a Special team')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('can_update_competition_team_level_of_competition', 'Can update Competition Team level of competition'), ('can_edit_competition_team_competitors', 'Can edit Competition Team competitors')],
            },
        ),
        migrations.CreateModel(
            name='SpecialTeamsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
