# Generated by Django 4.1.2 on 2022-10-11 06:12

import apps.core.project_requirements.utilities
import apps.geoposition.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='report',
            field=models.FileField(upload_to='Competition Report/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='venue_name',
            field=models.CharField(max_length=50, verbose_name='venue name'),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='specialteamscategories',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='name'),
        ),
    ]
