# Generated by Django 4.1.2 on 2022-10-11 06:12

import apps.registrations.models.scout_leaders
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='email',
            field=models.EmailField(blank=True, help_text='example@gmail.com (Leave blank if the Scout is not a Jasiri)', max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='investiture',
            field=models.BooleanField(db_index=True, default=False, verbose_name='investiture'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='jasiri_investiture',
            field=models.BooleanField(db_index=True, default=False, verbose_name='jasiri investiture'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Leave blank if the Scout is not a Jasiri', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='scout',
            name='section',
            field=models.CharField(choices=[('Sungura', 'Sungura'), ('Chipukizi', 'Chipukizi'), ('Mwamba', 'Mwamba'), ('Jasiri', 'Jasiri')], db_index=True, max_length=10, verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='scoutleader',
            name='date_of_birth',
            field=models.DateField(validators=[apps.registrations.models.scout_leaders.over_26_years], verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='scoutleader',
            name='email',
            field=models.EmailField(help_text='example@gmail.com', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='scoutleader',
            name='life_member',
            field=models.BooleanField(db_index=True, default=False, verbose_name='life member'),
        ),
        migrations.AlterField(
            model_name='scoutleader',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='scoutleader',
            name='tsc_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='tsc number'),
        ),
        migrations.AlterField(
            model_name='scoutleadercert',
            name='code',
            field=models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='scoutleadercert',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='date_warranted',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date warranted'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='sections',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sungura', 'Sungura'), ('Chipukizi', 'Chipukizi'), ('Mwamba', 'Mwamba'), ('Jasiri', 'Jasiri')], db_index=True, max_length=70, verbose_name='sections'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='sponsoring_authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sponsoring authority'),
        ),
    ]
