# Generated by Django 4.1.2 on 2022-10-11 06:12

import apps.core.project_requirements.utilities
import apps.geoposition.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth_programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='section',
            field=models.CharField(choices=[('Sungura', 'Sungura'), ('Chipukizi', 'Chipukizi'), ('Mwamba', 'Mwamba'), ('Jasiri', 'Jasiri')], db_index=True, max_length=10, verbose_name='sections'),
        ),
        migrations.AlterField(
            model_name='badgecamp',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='badgecamp',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='badgecamp',
            name='report',
            field=models.FileField(upload_to='Youth Programme Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='badgecamp',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='badgecamp',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='investiture',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='investiture',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='investiture',
            name='report',
            field=models.FileField(upload_to='Youth Programme Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='investiture',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='investiture',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='parkholiday',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='parkholiday',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='parkholiday',
            name='report',
            field=models.FileField(upload_to='Youth Programme Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='parkholiday',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='parkholiday',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='report',
            field=models.FileField(upload_to='Youth Programme Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='payments',
            field=models.BooleanField(db_index=True, default=False, verbose_name='payments'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='report',
            field=models.FileField(upload_to='Youth Programme Department/%Y/%m', validators=[apps.core.project_requirements.utilities.validate_file_extension], verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='rm',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
    ]
