# Generated by Django 4.1.2 on 2022-10-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doc_name', models.CharField(max_length=200, unique=True, verbose_name='Document name')),
                ('file', models.FileField(upload_to='Document/%Y/%m')),
                ('description', models.TextField()),
                ('date_to_cease_showing', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Form Name')),
                ('file', models.FileField(upload_to='Templates')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doc_name', models.CharField(max_length=200, unique=True, verbose_name='Document name')),
                ('file', models.FileField(upload_to='Document/%Y/%m')),
            ],
            options={
                'ordering': ['doc_name'],
            },
        ),
    ]
