# Generated by Django 4.1.2 on 2022-10-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_to_cease_showing',
            field=models.DateField(db_index=True, verbose_name='date to cease showing'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='Document/%Y/%m', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time stamp'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='file',
            field=models.FileField(upload_to='Templates', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='legaldocuments',
            name='file',
            field=models.FileField(upload_to='Document/%Y/%m', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='legaldocuments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time stamp'),
        ),
    ]
