# Generated by Django 4.1.3 on 2022-11-11 16:32

import apps.analytics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0002_taggeditem_taggeditem_analytics_t_content_2d9272_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=apps.analytics.models.views_limit, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
