# Generated by Django 4.1.2 on 2022-10-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(db_index=True, max_length=2, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('code', models.PositiveSmallIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='activeness')),
            ],
            options={
                'verbose_name': 'county',
                'verbose_name_plural': 'counties',
                'permissions': [('can_verify_county', 'Can verify Counties')],
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='activeness')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jurisdictions.county')),
            ],
            options={
                'verbose_name': 'sub_county',
                'verbose_name_plural': 'sub_counties',
                'permissions': [('can_verify_sub_county', 'Can verify SubCounty')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jurisdictions.subcounty')),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jurisdictions.country')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('level', models.CharField(choices=[('National', 'National Level'), ('Regional', 'Regional Level'), ('County', 'County Level'), ('SubCounty', 'SubCounty Level'), ('Zonal', 'Zonal Level'), ('Unit', 'Unit Level'), ('Scouts', 'Scouts Level')], db_index=True, max_length=20, verbose_name='level')),
            ],
            options={
                'verbose_name': 'rank',
                'verbose_name_plural': 'ranks',
                'ordering': ['level'],
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jurisdictions.region'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_country'),
        ),
        migrations.AddConstraint(
            model_name='county',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_county'),
        ),
    ]
