# Generated by Django 4.1.2 on 2022-10-09 06:36

import apps.geoposition.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefScoutAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Awards Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChuiBadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Awards Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountyParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Year')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Founderee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Founderee Year')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('report', models.FileField(upload_to='Founderee/%Y')),
                ('venue_name', models.CharField(max_length=50, verbose_name='Venue Name')),
                ('venue', apps.geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='FourBeadsAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Awards Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkBadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Awards Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatronsDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Year')),
                ('date', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutLeaderAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Awards Year')),
                ('name', models.CharField(db_index=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimbaBadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Awards Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreeBeadsAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Awards Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwoBeadsAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(default=2022, editable=False, verbose_name='Awards Year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
