# Generated by Django 4.1.2 on 2022-10-11 06:12

import apps.geoposition.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefscoutaward',
            name='award_date',
            field=models.DateField(verbose_name='awards date'),
        ),
        migrations.AlterField(
            model_name='chuibadgeaward',
            name='award_date',
            field=models.DateField(verbose_name='awards date'),
        ),
        migrations.AlterField(
            model_name='countyparticipants',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='founderee',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='founderee',
            name='report',
            field=models.FileField(upload_to='Founderee/%Y', verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='founderee',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='founderee',
            name='venue',
            field=apps.geoposition.fields.GeopositionField(max_length=42, verbose_name='venue'),
        ),
        migrations.AlterField(
            model_name='fourbeadsaward',
            name='award_date',
            field=models.DateField(verbose_name='awards date'),
        ),
        migrations.AlterField(
            model_name='linkbadgeaward',
            name='award_date',
            field=models.DateField(verbose_name='awards date'),
        ),
        migrations.AlterField(
            model_name='patronsday',
            name='date',
            field=models.DateField(db_index=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='scoutleaderaward',
            name='award_date',
            field=models.DateField(verbose_name='awards date'),
        ),
        migrations.AlterField(
            model_name='scoutleaderaward',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='simbabadgeaward',
            name='award_date',
            field=models.DateField(verbose_name='awards date'),
        ),
        migrations.AlterField(
            model_name='threebeadsaward',
            name='award_date',
            field=models.DateField(verbose_name='awards date'),
        ),
        migrations.AlterField(
            model_name='twobeadsaward',
            name='award_date',
            field=models.DateField(verbose_name='awards date'),
        ),
    ]
